using GGG.Components.Buildings;
using GGG.Components.Player;
using GGG.Shared;
using UnityEngine;

namespace GGG.Components.Buildings
{
    public class Farm : BuildingComponent
    {
        [Tooltip("Type of the farm")] 
        [SerializeField] private FarmTypes FarmType;
        [Tooltip("Resource to be generated by the farm")]
        [SerializeField] private Resource Resource;
        [Tooltip("Time of resource generation without upgrades")]
        [SerializeField] private float InitialGeneration;
        [Tooltip("Time of resource generation with the upgrades")] 
        [SerializeField] private float[] ResourcesGeneration;

        private PlayerManager _playerManager;
        
        private float _currentGeneration;
        private float _cooldownDelta;
        
        public override void Initialize()
        {
            _playerManager = PlayerManager.Instance;
            _currentGeneration = CurrentLevel == 1 ? InitialGeneration : ResourcesGeneration[CurrentLevel - 2];
        }

        public override void Interact()
        {
            _cooldownDelta -= Time.deltaTime;
            
            if (_cooldownDelta >= 0f) return;
            
            _playerManager.AddResource(Resource.GetKey(), 1);
            _cooldownDelta = _currentGeneration;
        }

        protected override void OnLevelUp()
        {
            _currentGeneration = ResourcesGeneration[CurrentLevel - 2];
        }

        public override void Boost()
        {
            if (CurrentLevel == 1) _currentGeneration -= InitialGeneration * 0.25f;
            else _currentGeneration -= ResourcesGeneration[CurrentLevel - 2] * 0.25f;
        }

        public override void EndBoost()
        {
            if (CurrentLevel == 1) _currentGeneration += InitialGeneration * 0.25f;
            else _currentGeneration += ResourcesGeneration[CurrentLevel - 2] * 0.25f;
        }
        
        /// <summary>
        /// Gets the type of the farm
        /// </summary>
        /// <returns>The type of the farm</returns>
        public FarmTypes GetFarmType() => FarmType;
        
        /// <summary>
        /// Gets the generated resource
        /// </summary>
        /// <returns>The generated resource</returns>
        public Resource GetResource() => Resource;

        /// <summary>
        /// Gets the generation based on the level of the building.
        /// </summary>
        /// <param name="level">Level of the building</param>
        /// <returns>The time (in seconds) between the generation of 1 resource</returns>
        public float GetGeneration() => _currentGeneration;

    }
}