using GGG.Components.Player;
using GGG.Shared;

using UnityEngine;
using System;

namespace GGG.Classes.Buildings
{
    [CreateAssetMenu(menuName = "Game/Buildings/Farm", fileName = "Farm")]
    public class Farm : Building {
        [Tooltip("Resource to be generated by the farm")]
        [SerializeField] private BasicResource Resource;
        [Tooltip("Amount of resource generated without upgrades")]
        [SerializeField] private int InitialGeneration;
        [Tooltip("Time between the generation of the resources")]
        [SerializeField] private int InitialCooldown;

        private float _cooldownDelta;
        
        
        public override void Interact() {
            if (_cooldownDelta >= 0) {
                _cooldownDelta -= Time.deltaTime;
                return;
            }
            
            PlayerManager.Instance.AddResource(Resource.GetResource(), InitialGeneration);
            _cooldownDelta = InitialCooldown;
        }
    }
}
